# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "SumTree",
]

@typing.final
class SumTree:
    r"""
    SumTree class
    A SumTree is a binary tree in which the value of a node is the sum of its direct children.
    As such, only leaves retain useful information.
    """
    @property
    def total(self) -> builtins.float:
        r"""
        The total cumulative sum
        """
    @property
    def capacity(self) -> builtins.int:
        r"""
        The maximal number of items (leaves) that the tree can store
        """
    def __new__(cls, capacity: builtins.int) -> SumTree: ...
    def add(self, value: builtins.float) -> None: ...
    def update(self, leaf_num: builtins.int, value: builtins.float) -> None:
        r"""
        Update the SumTree by changing a leaf value.
        The change is propagated up to the root.
        """
    def update_batched(self, leaf_nums: typing.Sequence[builtins.int], values: typing.Sequence[builtins.float]) -> None: ...
    def get(self, cumsum: builtins.float) -> tuple[builtins.int, builtins.float]:
        r"""
        Get the leaf number and leaf value that corresponds
        to the given cumulative sum.
        """
    def sample(self, n_samples: builtins.int) -> tuple[builtins.list[builtins.int], builtins.list[builtins.float]]:
        r"""
        Randomly sample `n_samples` leaves. Every leaf has a probability proportional
        to its value to be sampled.
        The same leaf could be sampled multiple times.
        """
    def sample_batched(self, n_samples: builtins.int) -> tuple[builtins.list[builtins.int], builtins.list[builtins.float]]:
        r"""
        Sample from the tree by splitting the tree value into `n_samples` batches.
        If tree.value is 60 and n = 3, one leaf will be selected in
        [0, 20), in [20, 40) and one in [40, 60)
        """
    def seed(self, seed_value: builtins.int) -> None: ...
    def is_empty(self) -> builtins.bool: ...
    def __deepcopy__(self, _memo: dict) -> SumTree: ...
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, leaf_num: builtins.int) -> builtins.float: ...
    def __setitem__(self, leaf_num: builtins.int, value: builtins.float) -> None: ...
    def __repr__(self) -> builtins.str: ...
    def __getstate__(self) -> tuple[builtins.list[builtins.float], builtins.int]:
        r"""
        Pickle protocol
        """
    def __setstate__(self, state: tuple[typing.Sequence[builtins.float], builtins.int]) -> None:
        r"""
        Pickle protocol
        """
    def __getnewargs__(self) -> tuple[builtins.int]:
        r"""
        Pickle protocol
        """

